name: CI

on: 
  push:
    branches:
      - master
# For scheduled deployment with Cron Jobs.
## Examples of cron schedule expressions:
### '0 * * * *': hourly
### '0 0 * * *': daily
### '0 0 1 * *': monthly
#   schedule:
#     - cron:  '0 0 * * *'

env:
  NODE_VER: '18.x'
  JAVA_DISTRIBUTION: 'zulu'
  JAVA_VER: 11

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: pip install requests
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        distribution: ${{ env.JAVA_DISTRIBUTION }}
        java-version: ${{ env.JAVA_VER }}

    - name: Verify Java version
      run: echo "Actual JDK in use -- "; java -version
    - name: Generate report
      run: bash ./run.sh
    - name: Deploy GitHub pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./reposense-report
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'
        commit_message: Rebuild pages at 
